// SPEC-OWNED — regenerated by `rune sync`. Edit the .rune spec, not this file.

export abstract class BookingBase {
  abstract checkCapability(capability: unknown): unknown;
  abstract toDto(): unknown;
}
