// Generated by rune manifest from ../../../../../tmp/runecheck2/client.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { interpret } from "./mod.ts";

Deno.test("interpret — happy path", async () => {
  // TODO: implement happy path test
});


Deno.test("unknown-code", async () => {
  // TODO: assert this fault path
});

