// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { book } from "./mod.ts";

Deno.test("book — happy path", async () => {
  // TODO: implement happy path test
});


Deno.test("not-supported", async () => {
  // TODO: assert this fault path
});


Deno.test("timeout", async () => {
  // TODO: assert this fault path
});


Deno.test("fail-closed", async () => {
  // TODO: assert this fault path
});

