// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { BookRequestDto } from "@/src/providers/dto/book-request.ts";
import type { BookResultDto } from "@/src/providers/dto/book-result.ts";

// Coordinator for [REQ] provider.book(BookRequestDto): BookResultDto.

export async function book(input: BookRequestDto): Promise<BookResultDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
