// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { NotifyDto } from "@/src/providers/dto/notify.ts";
import type { DeliveryDto } from "@/src/providers/dto/delivery.ts";

// Coordinator for [REQ] notification.send(NotifyDto): DeliveryDto.

export async function send(input: NotifyDto): Promise<DeliveryDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
