// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Polymorphic base for "Channel". Variants extend this.

export abstract class ChannelBase {
  abstract deliver(notifyDto: unknown): unknown;
}
