// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

Deno.test("Channel base — placeholder", () => {
  // TODO: tests against the base abstraction
});
