// Generated by rune manifest from fixtures/specs/todos.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a reference to an existing todo
export const TodoRefDtoSchema = z.object({

  id: z.unknown(), // TODO: tighten

});

export type TodoRefDto = z.infer<typeof TodoRefDtoSchema>;
