// Generated by rune manifest from specs/todos.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// input to create a new todo
export const CreateTodoDtoSchema = z.object({

  title: z.unknown(), // TODO: tighten

});

export type CreateTodoDto = z.infer<typeof CreateTodoDtoSchema>;
