// Generated by rune manifest from specs/todos.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a persisted todo list
export const ListDtoSchema = z.object({

  id: z.unknown(), // TODO: tighten

  name: z.unknown(), // TODO: tighten

});

export type ListDto = z.infer<typeof ListDtoSchema>;
