// Generated by rune manifest from specs/todos.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a persisted todo item
export const TodoDtoSchema = z.object({

  id: z.unknown(), // TODO: tighten

  title: z.unknown(), // TODO: tighten

  done: z.unknown(), // TODO: tighten

});

export type TodoDto = z.infer<typeof TodoDtoSchema>;
