// Generated by rune manifest from ../../../../../tmp/runecheck2/calendar.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a disallowed-arrival lookup; fails closed
export const BadCheckInDtoSchema = z.object({

  blocked: z.unknown(), // TODO: tighten

});

export type BadCheckInDto = z.infer<typeof BadCheckInDtoSchema>;
