// Generated by rune manifest from ../../../../../tmp/runecheck2/calendar.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// one assembled, directly-readable calendar row
export const CalendarRowDtoSchema = z.object({

  bookable: z.unknown(), // TODO: tighten

  charges: z.unknown(), // TODO: tighten

  minNights: z.unknown(), // TODO: tighten

  maxNights: z.unknown(), // TODO: tighten

  notes: z.unknown(), // TODO: tighten

});

export type CalendarRowDto = z.infer<typeof CalendarRowDtoSchema>;
