// Generated by rune manifest from ../../../../../tmp/runecheck2/calendar.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the (destination, room-type, check-in) row coordinate
export const CalendarKeyDtoSchema = z.object({

  destName: z.unknown(), // TODO: tighten

  roomType: z.unknown(), // TODO: tighten

  checkInDate: z.unknown(), // TODO: tighten

});

export type CalendarKeyDto = z.infer<typeof CalendarKeyDtoSchema>;
