// Generated by rune manifest from ../../../../../tmp/runecheck2/calendar.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the arrival date this row is keyed by
// rune declares: [TYP] checkInDate: string
export const checkInDateSchema = z.unknown(); // TODO: tighten to string
export type checkInDate = z.infer<typeof checkInDateSchema>;
