// Generated by rune manifest from ../../../../../tmp/runecheck2/calendar.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the destination key (load-bearing nesting key)
// rune declares: [TYP] destName: string
export const destNameSchema = z.unknown(); // TODO: tighten to string
export type destName = z.infer<typeof destNameSchema>;
