// Generated by rune manifest from ../../../../../tmp/runecheck2/calendar.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the developer/destination window submit just sold
export const InvalidationKeyDtoSchema = z.object({

  destName: z.unknown(), // TODO: tighten

  window: z.unknown(), // TODO: tighten

});

export type InvalidationKeyDto = z.infer<typeof InvalidationKeyDtoSchema>;
