// Generated by rune manifest from ../../../../../tmp/runecheck2/calendar.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the machine-fed booking-summary counts behind a gate
export const QuotaCountDtoSchema = z.object({

  today: z.unknown(), // TODO: tighten

  wtd: z.unknown(), // TODO: tighten

  mtd: z.unknown(), // TODO: tighten

});

export type QuotaCountDto = z.infer<typeof QuotaCountDtoSchema>;
