// Generated by rune manifest from ../../../../../tmp/runecheck2/calendar.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the developer/destination quota counter key
export const QuotaKeyDtoSchema = z.object({

  destName: z.unknown(), // TODO: tighten

});

export type QuotaKeyDto = z.infer<typeof QuotaKeyDtoSchema>;
