// Generated by rune manifest from ../../../../../tmp/runecheck2/calendar.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the room-type key in the inventory map
// rune declares: [TYP] roomType: string
export const roomTypeSchema = z.unknown(); // TODO: tighten to string
export type roomType = z.infer<typeof roomTypeSchema>;
