// Generated by rune manifest from ../../../../../tmp/runecheck2/calendar.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a sold-out backing-map lookup result
export const SoldOutDtoSchema = z.object({

  bookable: z.unknown(), // TODO: tighten

});

export type SoldOutDto = z.infer<typeof SoldOutDtoSchema>;
