// Generated by rune manifest from ../../../../../tmp/runecheck2/calendar.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the booking-window span in days to invalidate
// rune declares: [TYP] window: number
export const windowSchema = z.unknown(); // TODO: tighten to number
export type window = z.infer<typeof windowSchema>;
