// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { ChannelBase } from "@/src/providers/domain/business/channel/base/mod.ts";

// Variant: Email

export default class ChannelEmail extends ChannelBase {
  deliver(notifyDto: unknown): unknown {
    throw new Error("not implemented");
  }
}
