// Generated by rune manifest from ../../../../../tmp/runecheck2/sync.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the raw counts read for a summary
export const CountsDtoSchema = z.object({

  today: z.unknown(), // TODO: tighten

  wtd: z.unknown(), // TODO: tighten

  mtd: z.unknown(), // TODO: tighten

});

export type CountsDto = z.infer<typeof CountsDtoSchema>;
