// Generated by rune manifest from ../../../../../tmp/runecheck2/sync.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a held sold-out/bad-check-in write lock
export const LockDtoSchema = z.object({

  lockId: z.unknown(), // TODO: tighten

  held: z.unknown(), // TODO: tighten

});

export type LockDto = z.infer<typeof LockDtoSchema>;
