// Generated by rune manifest from ../../../../../tmp/runecheck2/sync.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a normalized partner availability payload
export const PartnerAvailDtoSchema = z.object({

  nights: z.unknown(), // TODO: tighten

});

export type PartnerAvailDto = z.infer<typeof PartnerAvailDtoSchema>;
