// Generated by rune manifest from ../../../../../tmp/runecheck2/sync.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a sold-out pruning request (60-day threshold)
export const PruneRequestDtoSchema = z.object({

  olderThanDays: z.unknown(), // TODO: tighten

});

export type PruneRequestDto = z.infer<typeof PruneRequestDtoSchema>;
