// Generated by rune manifest from ../../../../../tmp/runecheck2/sync.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// an inbound HI push-ingest webhook body
export const PushPayloadDtoSchema = z.object({

  developer: z.unknown(), // TODO: tighten

  payload: z.unknown(), // TODO: tighten

});

export type PushPayloadDto = z.infer<typeof PushPayloadDtoSchema>;
