// Generated by rune manifest from ../../../../../tmp/runecheck2/sync.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a per-developer availability pull request
export const RefreshRequestDtoSchema = z.object({

  developer: z.unknown(), // TODO: tighten

  destName: z.unknown(), // TODO: tighten

});

export type RefreshRequestDto = z.infer<typeof RefreshRequestDtoSchema>;
