// Generated by rune manifest from ../../../../../tmp/runecheck2/sync.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a quota-recompute request
export const SummarizeRequestDtoSchema = z.object({

  department: z.unknown(), // TODO: tighten

});

export type SummarizeRequestDto = z.infer<typeof SummarizeRequestDtoSchema>;
