// Generated by rune manifest from ../../../../../tmp/runecheck2/sync.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the recomputed booking-summary counts
export const SummaryDtoSchema = z.object({

  today: z.unknown(), // TODO: tighten

  wtd: z.unknown(), // TODO: tighten

  mtd: z.unknown(), // TODO: tighten

});

export type SummaryDto = z.infer<typeof SummaryDtoSchema>;
