// Generated by rune manifest from ../../../../../tmp/runecheck2/client.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the rendered charges/credits/card-split view
export const ChargeViewDtoSchema = z.object({

  lines: z.unknown(), // TODO: tighten

  total: z.unknown(), // TODO: tighten

  splits: z.unknown(), // TODO: tighten

});

export type ChargeViewDto = z.infer<typeof ChargeViewDtoSchema>;
