// Generated by rune manifest from ../../../../../tmp/runecheck2/client.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the engine's ordered charges, credits, and card split
export const ChargeListDtoSchema = z.object({

  charges: z.unknown(), // TODO: tighten

  credits: z.unknown(), // TODO: tighten

  card: z.unknown(), // TODO: tighten

});

export type ChargeListDto = z.infer<typeof ChargeListDtoSchema>;
