// Generated by rune manifest from ../../../../../tmp/runecheck2/client.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the submit numeric status code
// rune declares: [TYP] code: number
export const codeSchema = z.unknown(); // TODO: tighten to number
export type code = z.infer<typeof codeSchema>;
