// Generated by rune manifest from ../../../../../tmp/runecheck2/client.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the instant UI built from the request's own result
export const OptimisticViewDtoSchema = z.object({

  pending: z.unknown(), // TODO: tighten

  confirmation: z.unknown(), // TODO: tighten

});

export type OptimisticViewDto = z.infer<typeof OptimisticViewDtoSchema>;
