// Generated by rune manifest from ../../../../../tmp/runecheck2/client.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the per-code UI branch, not collapsed to 2xx
export const StatusViewDtoSchema = z.object({

  label: z.unknown(), // TODO: tighten

  severity: z.unknown(), // TODO: tighten

});

export type StatusViewDto = z.infer<typeof StatusViewDtoSchema>;
