// Generated by rune manifest from ../../../../../tmp/runecheck2/client.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a numeric submit status to interpret
export const StatusCodeDtoSchema = z.object({

  code: z.unknown(), // TODO: tighten

});

export type StatusCodeDto = z.infer<typeof StatusCodeDtoSchema>;
