// Generated by rune manifest from ../../../../../tmp/runecheck2/client.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the booking the user submitted from the browser
export const SubmitInputDtoSchema = z.object({

  guest: z.unknown(), // TODO: tighten

  room: z.unknown(), // TODO: tighten

  card: z.unknown(), // TODO: tighten

});

export type SubmitInputDto = z.infer<typeof SubmitInputDtoSchema>;
