// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import ChannelSms from "./mod.ts";

Deno.test("Channel/Sms — placeholder", () => {
  // TODO: variant-specific tests
});
