// Generated by rune manifest from ../../../../../tmp/runecheck2/submit.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { reschedule } from "./mod.ts";

Deno.test("reschedule — happy path", async () => {
  // TODO: implement happy path test
});


Deno.test("destination-mismatch", async () => {
  // TODO: assert this fault path
});


Deno.test("build-failed", async () => {
  // TODO: assert this fault path
});

