// Generated by rune manifest from ../../../../../tmp/runecheck2/submit.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { RescheduleDto } from "@/src/submit/dto/reschedule.ts";
import type { SubmitResultDto } from "@/src/submit/dto/submit-result.ts";

// Coordinator for [REQ] submission.reschedule(RescheduleDto): SubmitResultDto.

export async function reschedule(input: RescheduleDto): Promise<SubmitResultDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
