// Generated by rune manifest from ../../../../../tmp/runecheck2/submit.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { request } from "./mod.ts";

Deno.test("request — happy path", async () => {
  // TODO: implement happy path test
});


Deno.test("retry-prefix", async () => {
  // TODO: assert this fault path
});


Deno.test("timeout", async () => {
  // TODO: assert this fault path
});

