// Generated by rune manifest from ../../../../../tmp/runecheck2/submit.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { CancelRequestDto } from "@/src/submit/dto/cancel-request.ts";
import type { CancelResultDto } from "@/src/submit/dto/cancel-result.ts";

// Coordinator for [REQ] cancellation.request(CancelRequestDto): CancelResultDto.

export async function request(input: CancelRequestDto): Promise<CancelResultDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
