// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { buildRequest } from "./mod.ts";

Deno.test("buildRequest — happy path", async () => {
  // TODO: implement happy path test
});

