// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { BuildInputDto } from "@/src/engine/dto/build-input.ts";
import type { SubmitPayloadDto } from "@/src/engine/dto/submit-payload.ts";

// Coordinator for [REQ] guest.buildRequest(BuildInputDto): SubmitPayloadDto.

export async function buildRequest(input: BuildInputDto): Promise<SubmitPayloadDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
