// Generated by rune manifest from specs/todos.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Id } from "./mod.ts";

Deno.test("Id — placeholder", () => {
  // TODO: implement unit tests
});
