// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { load } from "./mod.ts";

Deno.test("load — happy path", async () => {
  // TODO: implement happy path test
});


Deno.test("timeout", async () => {
  // TODO: assert this fault path
});

