// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { PartnerBase } from "@/src/engine/domain/business/partner/base/mod.ts";

// Variant: Wyn

export default class PartnerWyn extends PartnerBase {
  confirm(liveConfirmDto: unknown): unknown {
    throw new Error("not implemented");
  }
}
