// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Polymorphic barrel for "Channel". Re-exports the active variant.
export { default } from "./implementations/sms/mod.ts";
