// SPEC-OWNED — regenerated by `rune sync`. Edit the .rune spec, not this file.

export abstract class ListBase {
  abstract fill(name: unknown): unknown;
  abstract save(listDto: unknown): unknown;
  abstract toDto(): unknown;
}
