// Generated by rune manifest from ../../../../../tmp/runecheck2/submit.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { PartnerBase } from "@/src/submit/domain/business/partner/base/mod.ts";

// Variant: Wyn

export default class PartnerWyn extends PartnerBase {
  cancel(cancelRequestDto: unknown): unknown {
    throw new Error("not implemented");
  }
}
