// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the available rooms after the pipeline
export const AvailabilityDtoSchema = z.object({

  rooms: z.unknown(), // TODO: tighten

});

export type AvailabilityDto = z.infer<typeof AvailabilityDtoSchema>;
