// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the selection to assemble a submit payload from
export const BuildInputDtoSchema = z.object({

  guest: z.unknown(), // TODO: tighten

  room: z.unknown(), // TODO: tighten

});

export type BuildInputDto = z.infer<typeof BuildInputDtoSchema>;
