// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the calendar half of the once-paid warm-up
export const CalendarBundleDtoSchema = z.object({

  soldOut: z.unknown(), // TODO: tighten

  quotas: z.unknown(), // TODO: tighten

});

export type CalendarBundleDto = z.infer<typeof CalendarBundleDtoSchema>;
