// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the ordered charge list plus passthrough credits
export const ChargesDtoSchema = z.object({

  charges: z.unknown(), // TODO: tighten

  credits: z.unknown(), // TODO: tighten

});

export type ChargesDto = z.infer<typeof ChargesDtoSchema>;
