// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the config half of the once-paid warm-up
export const ConfigBundleDtoSchema = z.object({

  developers: z.unknown(), // TODO: tighten

  departments: z.unknown(), // TODO: tighten

  features: z.unknown(), // TODO: tighten

});

export type ConfigBundleDto = z.infer<typeof ConfigBundleDtoSchema>;
