// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the display currency multiplied in at search time
// rune declares: [TYP] currency: string
export const currencySchema = z.unknown(); // TODO: tighten to string
export type currency = z.infer<typeof currencySchema>;
