// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a fully-loaded in-memory engine instance
export const EngineStateDtoSchema = z.object({

  loaded: z.unknown(), // TODO: tighten

  version: z.unknown(), // TODO: tighten

});

export type EngineStateDto = z.infer<typeof EngineStateDtoSchema>;
