// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the guest to run a FICO escape for
export const FicoRequestDtoSchema = z.object({

  guest: z.unknown(), // TODO: tighten

});

export type FicoRequestDto = z.infer<typeof FicoRequestDtoSchema>;
