// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the shotgun realtime availability check input
export const LiveConfirmDtoSchema = z.object({

  developer: z.unknown(), // TODO: tighten

  dates: z.unknown(), // TODO: tighten

});

export type LiveConfirmDto = z.infer<typeof LiveConfirmDtoSchema>;
