// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the disqualification notes; qualified iff empty
export const NotesDtoSchema = z.object({

  notes: z.unknown(), // TODO: tighten

});

export type NotesDto = z.infer<typeof NotesDtoSchema>;
