// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the guest and room to sum fee clauses for
export const PriceRequestDtoSchema = z.object({

  guest: z.unknown(), // TODO: tighten

  room: z.unknown(), // TODO: tighten

  currency: z.unknown(), // TODO: tighten

});

export type PriceRequestDto = z.infer<typeof PriceRequestDtoSchema>;
