// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the qualified developers and any NQ notes
export const QualifiedDtoSchema = z.object({

  developers: z.unknown(), // TODO: tighten

  notes: z.unknown(), // TODO: tighten

});

export type QualifiedDto = z.infer<typeof QualifiedDtoSchema>;
