// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the guest to run policy predicates against
export const QualifyRequestDtoSchema = z.object({

  guest: z.unknown(), // TODO: tighten

});

export type QualifyRequestDto = z.infer<typeof QualifyRequestDtoSchema>;
