// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the guest and booking window to search
export const SearchRequestDtoSchema = z.object({

  guest: z.unknown(), // TODO: tighten

  window: z.unknown(), // TODO: tighten

});

export type SearchRequestDto = z.infer<typeof SearchRequestDtoSchema>;
