// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the department session token for the warm-up
export const SessionTokenDtoSchema = z.object({

  token: z.unknown(), // TODO: tighten

});

export type SessionTokenDto = z.infer<typeof SessionTokenDtoSchema>;
