// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the locally-built payload handed to submit
export const SubmitPayloadDtoSchema = z.object({

  payload: z.unknown(), // TODO: tighten

});

export type SubmitPayloadDto = z.infer<typeof SubmitPayloadDtoSchema>;
