// Generated by rune manifest from ../../../../../tmp/runecheck2/sync.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { recompute } from "./mod.ts";

Deno.test("recompute — happy path", async () => {
  // TODO: implement happy path test
});


Deno.test("not-found", async () => {
  // TODO: assert this fault path
});


Deno.test("timeout", async () => {
  // TODO: assert this fault path
});

