// Generated by rune manifest from ../../../../../tmp/runecheck2/sync.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { SummarizeRequestDto } from "@/src/sync/dto/summarize-request.ts";
import type { SummaryDto } from "@/src/sync/dto/summary.ts";

// Coordinator for [REQ] summary.recompute(SummarizeRequestDto): SummaryDto.

export async function recompute(input: SummarizeRequestDto): Promise<SummaryDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
