// SPEC-OWNED — regenerated by `rune sync`. Edit the .rune spec, not this file.

export abstract class PayloadBase {
  abstract assemble(buildInputDto: unknown): unknown;
  abstract toDto(): unknown;
}
