// SPEC-OWNED — regenerated by `rune sync`. Edit the .rune spec, not this file.

export abstract class InventoryBase {
  abstract normalize(partnerAvailDto: unknown): unknown;
  abstract toDto(): unknown;
  abstract parse(pushPayloadDto: unknown): unknown;
}
