// Generated by rune manifest from ../../../../../tmp/runecheck2/sync.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Inventory } from "./mod.ts";

Deno.test("Inventory — placeholder", () => {
  // TODO: implement unit tests
});
