// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { CaptureDto } from "@/src/providers/dto/capture.ts";
import type { CaptureResultDto } from "@/src/providers/dto/capture-result.ts";

// Coordinator for [REQ] payment.capture(CaptureDto): CaptureResultDto.

export async function capture(input: CaptureDto): Promise<CaptureResultDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
