// Generated by rune manifest from ../../../../../tmp/runecheck2/submit.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { process } from "./mod.ts";

Deno.test("process — happy path", async () => {
  // TODO: implement happy path test
});


Deno.test("invalid-request", async () => {
  // TODO: assert this fault path
});


Deno.test("already-built", async () => {
  // TODO: assert this fault path
});


Deno.test("charge-declined", async () => {
  // TODO: assert this fault path
});


Deno.test("build-failed", async () => {
  // TODO: assert this fault path
});


Deno.test("capture-failed", async () => {
  // TODO: assert this fault path
});


Deno.test("timeout", async () => {
  // TODO: assert this fault path
});

