// Generated by rune manifest from ../../../../../tmp/runecheck2/submit.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { SubmitRequestDto } from "@/src/submit/dto/submit-request.ts";
import type { SubmitResultDto } from "@/src/submit/dto/submit-result.ts";

// Coordinator for [REQ] submission.process(SubmitRequestDto): SubmitResultDto.

export async function process(input: SubmitRequestDto): Promise<SubmitResultDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
