// Generated by rune manifest from corpus/valid/entrypoint.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { PayDto } from "@/src/checkout/dto/pay.ts";
import type { ReceiptDto } from "@/src/checkout/dto/receipt.ts";
import { Payment } from "@/src/checkout/domain/business/payment/mod.ts";
import { Payment as PaymentData } from "@/src/checkout/domain/data/payment/mod.ts";

// Coordinator for [REQ] payment.pay(PayDto): ReceiptDto.
export async function pay(input: PayDto): Promise<ReceiptDto> {
  const paymentData = new PaymentData();

  // reads — load inputs through the data adapters
  const paymentCharge = await paymentData.charge(undefined as never) as ReceiptDto;

  // core — pure business logic, no I/O
  const out = payCore(input, paymentCharge);

  return out.result;
}

// Pure business logic for payment.pay — no I/O. Takes the
// request input and the dtos the reads loaded; returns the result.
function payCore(input: PayDto, paymentCharge: ReceiptDto): { result: ReceiptDto } {
  const payment = new Payment();
  // TODO: run the pure steps on payment, build the dtos
  throw new Error("not implemented");
}
