// Generated by rune manifest from ../../../../../tmp/runecheck2/calendar.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { CalendarKeyDto } from "@/src/calendar/dto/calendar-key.ts";
import type { CalendarRowDto } from "@/src/calendar/dto/calendar-row.ts";

// Coordinator for [REQ] calendar.read(CalendarKeyDto): CalendarRowDto.

export async function read(input: CalendarKeyDto): Promise<CalendarRowDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
