// Generated by rune manifest from todos.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// input to create a new list
export const CreateListDtoSchema = z.object({

  name: z.unknown(), // TODO: tighten

});

export type CreateListDto = z.infer<typeof CreateListDtoSchema>;
