// SPEC-OWNED — regenerated by `rune sync`. Edit the .rune spec, not this file.

export abstract class EngineBase {
  abstract warmUp(configBundleDto: unknown): unknown;
  abstract toDto(): unknown;
}
