// Generated by rune manifest from todos.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { TodoRefDto } from "@/src/todos/dto/todo-ref.ts";
import type { TodoDto } from "@/src/todos/dto/todo.ts";

// Coordinator for [REQ] todo.discard(TodoRefDto): TodoDto.

export async function discard(input: TodoRefDto): Promise<TodoDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
