// SPEC-OWNED — regenerated by `rune sync`. Edit the .rune spec, not this file.

export abstract class LockBase {
  abstract acquire(refreshRequestDto: unknown): unknown;
  abstract release(lockDto: unknown): unknown;
}
