// Generated by rune manifest from ../../../../../tmp/runecheck2/sync.rune.
// Edit the body. Re-running manifest will not overwrite this file.

Deno.test("lock — connectivity", () => {
  // TODO: smoke test that verifies the boundary is reachable
});


Deno.test("locked", async () => {
  // TODO: assert this fault path
});

