// Generated by rune manifest from todos.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { complete } from "./mod.ts";

Deno.test("complete — happy path", async () => {
  // TODO: implement happy path test
});


Deno.test("not-found", async () => {
  // TODO: assert this fault path
});


Deno.test("timeout", async () => {
  // TODO: assert this fault path
});

