// Generated by rune manifest from specs/todos.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { CreateTodoDto } from "@/src/todos/dto/create-todo.ts";
import type { TodoDto } from "@/src/todos/dto/todo.ts";

// Coordinator for [REQ] todo.add(CreateTodoDto): TodoDto.

export async function add(input: CreateTodoDto): Promise<TodoDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
