// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Polymorphic barrel for "Partner". Re-exports the active variant.
export { default } from "./implementations/hi/mod.ts";
