// SPEC-OWNED — regenerated by `rune sync`. Edit the .rune spec, not this file.

export abstract class BookingSummaryBase {
  abstract read(summarizeRequestDto: unknown): unknown;
  abstract write(summaryDto: unknown): unknown;
}
