// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { PriceRequestDto } from "@/src/engine/dto/price-request.ts";
import type { ChargesDto } from "@/src/engine/dto/charges.ts";

// Coordinator for [REQ] guest.price(PriceRequestDto): ChargesDto.

export async function price(input: PriceRequestDto): Promise<ChargesDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
