// Generated by rune manifest from ../../../../../tmp/runecheck2/sync.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { refresh } from "./mod.ts";

Deno.test("refresh — happy path", async () => {
  // TODO: implement happy path test
});


Deno.test("locked", async () => {
  // TODO: assert this fault path
});


Deno.test("timeout", async () => {
  // TODO: assert this fault path
});

