// Generated by rune manifest from ../../../../../tmp/runecheck2/sync.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { RefreshRequestDto } from "@/src/sync/dto/refresh-request.ts";
import type { SyncResultDto } from "@/src/sync/dto/sync-result.ts";

// Coordinator for [REQ] inventory.refresh(RefreshRequestDto): SyncResultDto.

export async function refresh(input: RefreshRequestDto): Promise<SyncResultDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
