// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { FicoRequestDto } from "@/src/engine/dto/fico-request.ts";
import type { FicoResultDto } from "@/src/engine/dto/fico-result.ts";

// Coordinator for [REQ] guest.checkFico(FicoRequestDto): FicoResultDto.

export async function checkFico(input: FicoRequestDto): Promise<FicoResultDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
