// SPEC-OWNED — regenerated by `rune sync`. Edit the .rune spec, not this file.

export abstract class SearchBase {
  abstract runPipeline(searchRequestDto: unknown): unknown;
  abstract toDto(): unknown;
}
