// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Search } from "./mod.ts";

Deno.test("Search — placeholder", () => {
  // TODO: implement unit tests
});
