// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { LiveConfirmDto } from "@/src/engine/dto/live-confirm.ts";
import type { LiveResultDto } from "@/src/engine/dto/live-result.ts";

// Coordinator for [REQ] guest.liveConfirm(LiveConfirmDto): LiveResultDto.

export async function liveConfirm(input: LiveConfirmDto): Promise<LiveResultDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
