-- Rune file icon for nvim-web-devicons
-- This file is auto-generated by `rune install`

local ok, devicons = pcall(require, "nvim-web-devicons")
if ok then
  devicons.set_icon({
    rune = {
      icon = "ᚱ",
      color = "#89babf",
      name = "Rune"
    }
  })
end
