// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Record } from "./mod.ts";

Deno.test("Record — placeholder", () => {
  // TODO: implement unit tests
});
