// SPEC-OWNED — regenerated by `rune sync`. Edit the .rune spec, not this file.

export abstract class CalendarBase {
  abstract assemble(soldOutDto: unknown): unknown;
  abstract toDto(): unknown;
}
