// Generated by rune manifest from ../../../../../tmp/runecheck2/calendar.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Calendar } from "./mod.ts";

Deno.test("Calendar — placeholder", () => {
  // TODO: implement unit tests
});
