// SPEC-OWNED — regenerated by `rune sync`. Edit the .rune spec, not this file.

export abstract class SubmissionBase {
  abstract validate(submitRequestDto: unknown): unknown;
  abstract toDto(): unknown;
  abstract matchDestination(rescheduleDto: unknown): unknown;
}
