// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { authorize } from "./mod.ts";

Deno.test("authorize — happy path", async () => {
  // TODO: implement happy path test
});


Deno.test("declined", async () => {
  // TODO: assert this fault path
});


Deno.test("timeout", async () => {
  // TODO: assert this fault path
});

