// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { AuthorizeDto } from "@/src/providers/dto/authorize.ts";
import type { AuthResultDto } from "@/src/providers/dto/auth-result.ts";

// Coordinator for [REQ] payment.authorize(AuthorizeDto): AuthResultDto.

export async function authorize(input: AuthorizeDto): Promise<AuthResultDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
