// Generated by rune manifest from ../../../../../tmp/runecheck2/calendar.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Invalidation } from "./mod.ts";

Deno.test("Invalidation — placeholder", () => {
  // TODO: implement unit tests
});
