// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { QualifyRequestDto } from "@/src/engine/dto/qualify-request.ts";
import type { QualifiedDto } from "@/src/engine/dto/qualified.ts";

// Coordinator for [REQ] guest.qualify(QualifyRequestDto): QualifiedDto.

export async function qualify(input: QualifyRequestDto): Promise<QualifiedDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
