// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { LegWriteDto } from "@/src/providers/dto/leg-write.ts";
import type { LegRefDto } from "@/src/providers/dto/leg-ref.ts";

// Coordinator for [REQ] records.writeLeg(LegWriteDto): LegRefDto.

export async function writeLeg(input: LegWriteDto): Promise<LegRefDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
