// Generated by rune manifest from ../../../../../tmp/runecheck2/submit.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import PartnerHi from "./mod.ts";

Deno.test("Partner/Hi — placeholder", () => {
  // TODO: variant-specific tests
});
