// SPEC-OWNED — regenerated by `rune sync`. Edit the .rune spec, not this file.

export abstract class RefundBase {
  abstract validateResponse(refundDto: unknown): unknown;
  abstract toDto(): unknown;
}
