// Generated by rune manifest from ../../../../../tmp/runecheck2/submit.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Refund } from "./mod.ts";

Deno.test("Refund — placeholder", () => {
  // TODO: implement unit tests
});
