// SPEC-OWNED — regenerated by `rune sync`. Edit the .rune spec, not this file.

export abstract class GatewayBase {
  abstract authorize(authorizeDto: unknown): unknown;
  abstract capture(captureDto: unknown): unknown;
}
