// SPEC-OWNED — regenerated by `rune sync`. Edit the .rune spec, not this file.

export abstract class QualifierBase {
  abstract runGates(qualifyRequestDto: unknown): unknown;
  abstract collectNotes(): unknown;
  abstract toDto(): unknown;
}
