// SPEC-OWNED — regenerated by `rune sync`. Edit the .rune spec, not this file.

export abstract class SoldOutBase {
  abstract write(partnerAvailDto: unknown): unknown;
  abstract applyPush(pushPayloadDto: unknown): unknown;
  abstract expire(pruneRequestDto: unknown): unknown;
}
