// SPEC-OWNED — regenerated by `rune sync`. Edit the .rune spec, not this file.

export abstract class ChargeViewBase {
  abstract orderCharges(chargeListDto: unknown): unknown;
  abstract applyCredits(chargeListDto: unknown): unknown;
  abstract splitCard(chargeListDto: unknown): unknown;
  abstract toDto(): unknown;
}
