// SPEC-OWNED — regenerated by `rune sync`. Edit the .rune spec, not this file.

export abstract class TodoBase {
  abstract fill(title: unknown): unknown;
  abstract save(todoDto: unknown): unknown;
  abstract toDto(): unknown;
  abstract load(id: unknown): unknown;
  abstract markDone(): unknown;
  abstract archive(): unknown;
}
