// Generated by rune manifest from fixtures/specs/todos.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Todo } from "./mod.ts";

Deno.test("Todo — placeholder", () => {
  // TODO: implement unit tests
});
