// Generated by rune manifest from ../../../../../tmp/runecheck2/client.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { render } from "./mod.ts";

Deno.test("render — happy path", async () => {
  // TODO: implement happy path test
});

