// Generated by rune manifest from ../../../../../tmp/runecheck2/client.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { ChargeListDto } from "@/src/client/dto/charge-list.ts";
import type { ChargeViewDto } from "@/src/client/dto/charge-view.ts";

// Coordinator for [REQ] charges.render(ChargeListDto): ChargeViewDto.

export async function render(input: ChargeListDto): Promise<ChargeViewDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
