// SPEC-OWNED — regenerated by `rune sync`. Edit the .rune spec, not this file.

export abstract class PaymentBase {
  abstract authorize(submitRequestDto: unknown): unknown;
  abstract capture(authDto: unknown): unknown;
  abstract refund(refundRequestDto: unknown): unknown;
}
