// SPEC-OWNED — regenerated by `rune sync`. Edit the .rune spec, not this file.

export abstract class PartnerBase {
  abstract fetchCalendar(calendarPullDto: unknown): unknown;
  abstract submitBooking(bookRequestDto: unknown): unknown;
}
