// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

Deno.test("partner — connectivity", () => {
  // TODO: smoke test that verifies the boundary is reachable
});


Deno.test("timeout", async () => {
  // TODO: assert this fault path
});


Deno.test("fail-closed", async () => {
  // TODO: assert this fault path
});

