// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a card authorization request
export const AuthorizeDtoSchema = z.object({

  card: z.unknown(), // TODO: tighten

  amount: z.unknown(), // TODO: tighten

});

export type AuthorizeDto = z.infer<typeof AuthorizeDtoSchema>;
