// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a request to book a partner
export const BookRequestDtoSchema = z.object({

  guest: z.unknown(), // TODO: tighten

  room: z.unknown(), // TODO: tighten

  capability: z.unknown(), // TODO: tighten

});

export type BookRequestDto = z.infer<typeof BookRequestDtoSchema>;
