// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a request to pull a partner's calendar
export const CalendarPullDtoSchema = z.object({

  developer: z.unknown(), // TODO: tighten

  destName: z.unknown(), // TODO: tighten

  capability: z.unknown(), // TODO: tighten

});

export type CalendarPullDto = z.infer<typeof CalendarPullDtoSchema>;
