// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a declared provider capability name
// rune declares: [TYP] capability: string
export const capabilitySchema = z.unknown(); // TODO: tighten to string
export type capability = z.infer<typeof capabilitySchema>;
