// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a capture of a prior authorization
export const CaptureDtoSchema = z.object({

  authId: z.unknown(), // TODO: tighten

  amount: z.unknown(), // TODO: tighten

});

export type CaptureDto = z.infer<typeof CaptureDtoSchema>;
