// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// proof a notification was dispatched
export const DeliveryDtoSchema = z.object({

  messageId: z.unknown(), // TODO: tighten

  sent: z.unknown(), // TODO: tighten

});

export type DeliveryDto = z.infer<typeof DeliveryDtoSchema>;
