// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a CRM leg write, enqueued write-behind
export const LegWriteDtoSchema = z.object({

  reservation: z.unknown(), // TODO: tighten

  leg: z.unknown(), // TODO: tighten

});

export type LegWriteDto = z.infer<typeof LegWriteDtoSchema>;
