// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the queued leg reference
export const LegRefDtoSchema = z.object({

  legId: z.unknown(), // TODO: tighten

  queued: z.unknown(), // TODO: tighten

});

export type LegRefDto = z.infer<typeof LegRefDtoSchema>;
