// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// an outbound sms or email
export const NotifyDtoSchema = z.object({

  recipient: z.unknown(), // TODO: tighten

  body: z.unknown(), // TODO: tighten

});

export type NotifyDto = z.infer<typeof NotifyDtoSchema>;
