// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a partner's realtime night list
export const PartnerCalendarDtoSchema = z.object({

  nights: z.unknown(), // TODO: tighten

});

export type PartnerCalendarDto = z.infer<typeof PartnerCalendarDtoSchema>;
