// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { search } from "./mod.ts";

Deno.test("search — happy path", async () => {
  // TODO: implement happy path test
});


Deno.test("no-rooms", async () => {
  // TODO: assert this fault path
});

