// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { SearchRequestDto } from "@/src/engine/dto/search-request.ts";
import type { AvailabilityDto } from "@/src/engine/dto/availability.ts";

// Coordinator for [REQ] guest.search(SearchRequestDto): AvailabilityDto.

export async function search(input: SearchRequestDto): Promise<AvailabilityDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
