// Generated by rune manifest from ../../../../../tmp/runecheck2/providers.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { CalendarPullDto } from "@/src/providers/dto/calendar-pull.ts";
import type { PartnerCalendarDto } from "@/src/providers/dto/partner-calendar.ts";

// Coordinator for [REQ] provider.getCalendar(CalendarPullDto): PartnerCalendarDto.

export async function getCalendar(input: CalendarPullDto): Promise<PartnerCalendarDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
