// Generated by rune manifest from ../../../../../tmp/runecheck2/client.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { submitOptimistic } from "./mod.ts";

Deno.test("submitOptimistic — happy path", async () => {
  // TODO: implement happy path test
});


Deno.test("submit-failed", async () => {
  // TODO: assert this fault path
});

