// Generated by rune manifest from ../../../../../tmp/runecheck2/client.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { SubmitInputDto } from "@/src/client/dto/submit-input.ts";
import type { OptimisticViewDto } from "@/src/client/dto/optimistic-view.ts";

// Coordinator for [REQ] booking.submitOptimistic(SubmitInputDto): OptimisticViewDto.

export async function submitOptimistic(input: SubmitInputDto): Promise<OptimisticViewDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
