// Generated by rune manifest from corpus/valid/entrypoint.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// the order id
// rune declares: [TYP] id: string
export type Id = string;
