// Generated by rune manifest from corpus/valid/entrypoint.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// the item to order
// rune declares: [TYP] item: string
export type Item = string;
