// Generated by rune manifest from corpus/valid/entrypoint.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// a new order to create
export class NewOrderDto {
  @IsString()
  item!: string;
}
