// Generated by rune manifest from corpus/valid/entrypoint.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { IsString } from "class-validator";

// a created order
export class OrderDto {
  @IsString()
  id!: string;

  @IsString()
  item!: string;
}
