// SPEC-OWNED — regenerated by `rune sync`. Edit the .rune spec, not this file.

export abstract class ChargesBase {
  abstract sumFees(priceRequestDto: unknown): unknown;
  abstract applyCurrency(currency: unknown): unknown;
  abstract toDto(): unknown;
}
