// Generated by rune manifest from ../../../../../tmp/runecheck2/submit.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// an authorize-only result; capture comes later
export const AuthDtoSchema = z.object({

  authId: z.unknown(), // TODO: tighten

  approved: z.unknown(), // TODO: tighten

});

export type AuthDto = z.infer<typeof AuthDtoSchema>;
