// Generated by rune manifest from ../../../../../tmp/runecheck2/submit.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the partner book result
export const BookDtoSchema = z.object({

  confirmation: z.unknown(), // TODO: tighten

  booked: z.unknown(), // TODO: tighten

});

export type BookDto = z.infer<typeof BookDtoSchema>;
