// Generated by rune manifest from ../../../../../tmp/runecheck2/submit.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the partner cancel result
export const CancelDtoSchema = z.object({

  cancelled: z.unknown(), // TODO: tighten

});

export type CancelDto = z.infer<typeof CancelDtoSchema>;
