// Generated by rune manifest from ../../../../../tmp/runecheck2/submit.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a partner-specific cancel request
export const CancelRequestDtoSchema = z.object({

  legId: z.unknown(), // TODO: tighten

  developer: z.unknown(), // TODO: tighten

});

export type CancelRequestDto = z.infer<typeof CancelRequestDtoSchema>;
