// Generated by rune manifest from ../../../../../tmp/runecheck2/submit.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the capture taken only after the partner books
export const CaptureDtoSchema = z.object({

  captured: z.unknown(), // TODO: tighten

});

export type CaptureDto = z.infer<typeof CaptureDtoSchema>;
