// Generated by rune manifest from ../../../../../tmp/runecheck2/submit.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the deterministic pending-doc idempotency check
export const PendingDtoSchema = z.object({

  legId: z.unknown(), // TODO: tighten

  built: z.unknown(), // TODO: tighten

});

export type PendingDto = z.infer<typeof PendingDtoSchema>;
