// Generated by rune manifest from ../../../../../tmp/runecheck2/submit.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a refund/void request
export const RefundRequestDtoSchema = z.object({

  legId: z.unknown(), // TODO: tighten

  amount: z.unknown(), // TODO: tighten

});

export type RefundRequestDto = z.infer<typeof RefundRequestDtoSchema>;
