// Generated by rune manifest from ../../../../../tmp/runecheck2/submit.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// the gateway refund response, to be validated
export const RefundDtoSchema = z.object({

  refundId: z.unknown(), // TODO: tighten

  refunded: z.unknown(), // TODO: tighten

});

export type RefundDto = z.infer<typeof RefundDtoSchema>;
