// Generated by rune manifest from ../../../../../tmp/runecheck2/submit.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a reschedule keyed by an existing leg id
export const RescheduleDtoSchema = z.object({

  legId: z.unknown(), // TODO: tighten

  destName: z.unknown(), // TODO: tighten

});

export type RescheduleDto = z.infer<typeof RescheduleDtoSchema>;
