// Generated by rune manifest from ../../../../../tmp/runecheck2/submit.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { z } from "#zod";

// a booking submission carrying the card
export const SubmitRequestDtoSchema = z.object({

  guest: z.unknown(), // TODO: tighten

  room: z.unknown(), // TODO: tighten

  card: z.unknown(), // TODO: tighten

});

export type SubmitRequestDto = z.infer<typeof SubmitRequestDtoSchema>;
