// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Polymorphic base for "Partner". Variants extend this.

export abstract class PartnerBase {
  abstract confirm(liveConfirmDto: unknown): unknown;
}
