// Generated by rune manifest from ../../../../../tmp/runecheck2/engine.rune.
// Edit the body. Re-running manifest will not overwrite this file.

Deno.test("Partner base — placeholder", () => {
  // TODO: tests against the base abstraction
});
