// Generated by rune manifest from ../../../../../tmp/runecheck2/submit.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { issue } from "./mod.ts";

Deno.test("issue — happy path", async () => {
  // TODO: implement happy path test
});


Deno.test("refund-failed", async () => {
  // TODO: assert this fault path
});


Deno.test("invalid-response", async () => {
  // TODO: assert this fault path
});

