// Generated by rune manifest from ../../../../../tmp/runecheck2/submit.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { RefundRequestDto } from "@/src/submit/dto/refund-request.ts";
import type { RefundResultDto } from "@/src/submit/dto/refund-result.ts";

// Coordinator for [REQ] refund.issue(RefundRequestDto): RefundResultDto.

export async function issue(input: RefundRequestDto): Promise<RefundResultDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
