// Generated by rune manifest from ../../../../../tmp/runecheck2/submit.rune.
// Edit the body. Re-running manifest will not overwrite this file.

// Polymorphic base for "Partner". Variants extend this.

export abstract class PartnerBase {
  abstract cancel(cancelRequestDto: unknown): unknown;
}
