// Generated by rune manifest from corpus/valid/entrypoint.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { httpModule } from "./mod.ts";
import { bootstrapServer, exerciseEndpoints } from "@mrg-keystone/keep";
import { assertEquals } from "#std/assert";

// Fill the coordinator bodies, then run with RUNE_E2E=1 to drive every endpoint
// to green (orders by @Endpoint order, chains outputs into inputs via bind).
Deno.test({
  name: "checkout/http — endpoints run and chain",
  ignore: !Deno.env.get("RUNE_E2E"),
  fn: async () => {
    const api = await bootstrapServer("checkout", httpModule, { swagger: true });
    try {
      const report = await exerciseEndpoints({ api });
      assertEquals(report.failed.map((r) => r.id), []);
    } finally {
      await api.stop();
    }
  },
});
