// Generated by rune manifest from corpus/valid/entrypoint.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Endpoint, EndpointController, endpointModule } from "@mrg-keystone/keep";
import { NewOrderDto } from "@/src/checkout/dto/new-order.ts";
import { OrderDto } from "@/src/checkout/dto/order.ts";
import { PayDto } from "@/src/checkout/dto/pay.ts";
import { ReceiptDto } from "@/src/checkout/dto/receipt.ts";
import { create as orderCreate } from "@/src/checkout/domain/coordinators/order-create/mod.ts";
import { pay as paymentPay } from "@/src/checkout/domain/coordinators/payment-pay/mod.ts";

@EndpointController("http")
export class HttpController {
  @Endpoint({ input: NewOrderDto, output: OrderDto, order: 1 })
  createOrder(body: NewOrderDto): Promise<OrderDto> {
    return orderCreate(body);
  }

  @Endpoint({ input: PayDto, output: ReceiptDto, order: 2, dependsOn: ["createOrder"], bind: {"id":"createOrder.id"} })
  payOrder(body: PayDto): Promise<ReceiptDto> {
    return paymentPay(body);
  }
}

export const httpModule = endpointModule("Checkout", [HttpController]);
