// SPEC-OWNED — regenerated by `rune sync`. Edit the .rune spec, not this file.

export abstract class OptimisticBase {
  abstract renderFromResult(submitInputDto: unknown): unknown;
  abstract reconcile(submitResultDto: unknown): unknown;
  abstract toDto(): unknown;
}
