// Generated by rune manifest from ../../../../../tmp/runecheck2/client.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { Optimistic } from "./mod.ts";

Deno.test("Optimistic — placeholder", () => {
  // TODO: implement unit tests
});
