// Generated by rune manifest from ../../../../../tmp/runecheck2/calendar.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import type { QuotaKeyDto } from "@/src/calendar/dto/quota-key.ts";
import type { QuotaCountDto } from "@/src/calendar/dto/quota-count.ts";

// Coordinator for [REQ] quota.count(QuotaKeyDto): QuotaCountDto.

export async function count(input: QuotaKeyDto): Promise<QuotaCountDto> {
  // TODO: implement the flow as declared in the rune.
  throw new Error("not implemented");
}
