// Generated by rune manifest from specs/todos.rune.
// Edit the body. Re-running manifest will not overwrite this file.

import { discard } from "./mod.ts";

Deno.test("discard — happy path", async () => {
  // TODO: implement happy path test
});


Deno.test("not-found", async () => {
  // TODO: assert this fault path
});


Deno.test("timeout", async () => {
  // TODO: assert this fault path
});

